### PR TITLE
feat: support MSVC with Ninja regardless of the environment variables

### PR DESCRIPTION
**Pull request by aminya**
Automatically find MSVC compilers upon request even if the environment variables are not set and the MSVC generator is not used. This uses the MSVC toolchain by @MarkSchofield

https://github.com/MarkSchofield/Toolchain

How to test:
```ps1
$env:CC="cl"; $env:CXX="cl"; 
task test
```
Which runs [these commands](https://github.com/cpp-best-practices/project_options/blob/030ddd088da1631b97c8e6e2fcdef8b1a03b2787/Taskfile.yml#L6)

- [x] Download vswhere if missing (https://github.com/MarkSchofield/Toolchain/issues/11)
- [x] verify that cl.exe and ninja work together regardless of the environment variables of the current shell
- [x] The build now works fine, but clang-tidy does not work with MSVC (#54)

### CODE REVIEW

**Comment by aminya** [comment]
The error I get when running the tests
```cmake
FAILED: CMakeFiles/main.dir/Debug/main.cpp.obj
"C:\Program Files\CMake\bin\cmake.exe" -E __run_co_compile --launcher=C:/tools/msys64/mingw64/bin/ccache.exe --cppcheck="C:/Program Files/Cppcheck/cppcheck.exe;--suppress=missingInclude;--enable=all;--inline-suppr;--inconclusive;--std=c++17" --source=C:\project_options\test\main.cpp -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DFMT_LOCALE -DFMT_SHARED -DCMAKE_INTDIR=\"Debug\" -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\include -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\share\eigen3\..\..\include\eigen3 -external:W0 /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd /diagnostics:column /W4 /w14242 /w14254 /w14263 /w14265 /w14287 /we4289 /w14296 /w14311 /w14545 /w14546 /w14547 /w14549 /w14555 /w14619 /w14640 /w14826 /w14905 /w14906 /w14928 /permissive- -std:c++17 /showIncludes /FoCMakeFiles\main.dir\Debug\main.cpp.obj /FdCMakeFiles\main.dir\Debug\ /FS -c C:\project_options\test\main.cpp
Checking C:\project_options\test\main.cpp ...
Checking C:\project_options\test\main.cpp: FMT_LOCALE=1;FMT_SHARED=1;CMAKE_INTDIR="Debug";WIN32=1;_WINDOWS=1...
C:\project_options\test\build\vcpkg_installed\x64-windows\include\fmt/core.h(11,10): fatal error C1083: Cannot open include file: 'cstdio': No such file or directory
ninja: build stopped: subcommand failed.
```

**Comment by aminya** [comment]
The build now works fine, but clang-tidy does not work with MSVC

```cmake
FAILED: CMakeFiles/main.dir/Debug/main.cpp.obj
"C:\Program Files\CMake\bin\cmake.exe" -E __run_co_compile --launcher=C:/tools/msys64/mingw64/bin/ccache.exe --tidy="C:/Program Files/LLVM/bin/clang-tidy.exe;-extra-arg=-Wno-unknown-warning-option;-extra-arg=-std=c++17;--extra-arg-before=--driver-mode=cl" --cppcheck="C:/Program Files/Cppcheck/cppcheck.exe;--suppress=missingInclude;--enable=all;--inline-suppr;--inconclusive;--std=c++17" --source=C:\project_options\test\main.cpp -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DFMT_LOCALE -DFMT_SHARED -DCMAKE_INTDIR=\"Debug\" -external:I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\ATLMFC\include" -external:I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\include -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\share\eigen3\..\..\include\eigen3 -external:W0 /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd /diagnostics:column /W4 /w14242 /w14254 /w14263 /w14265 /w14287 /we4289 /w14296 /w14311 /w14545 /w14546 /w14547 /w14549 /w14555 /w14619 /w14640 /w14826 /w14905 /w14906 /w14928 /permissive- -std:c++17 /showIncludes /FoCMakeFiles\main.dir\Debug\main.cpp.obj /FdCMakeFiles\main.dir\Debug\ /FS -c C:\project_options\test\main.cpp
warning: unknown argument ignored in clang-cl: '-std=c++17' [clang-diagnostic-unknown-argument]
C:\project_options\test\main.cpp:2:10: error: 'fmt/core.h' file not found [clang-diagnostic-error]
#include <fmt/core.h>
         ^~~~~~~~~~~~
23598 warnings and 1 error generated.
Error while processing C:\project_options\test\main.cpp.
Suppressed 23597 warnings (23597 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
ninja: build stopped: subcommand failed.

```

**Review by aminya — COMMENTED** [review]
Now, this warning is given. It seems that it is from clang-cl

```
warning: argument unused during compilation: '-external:W0' [clang-diagnostic-unused-command-line-argument]
```

All the other things work without any issue 🎉

**Comment by lefticus** [comment]
> warning: unknown argument ignored in clang-cl: '-std=c++17' [clang-diagnostic-unknown-argument]

It seems some wrong flags are still be passed to clang-cl - namely the C++ version switch

**Comment by aminya** [comment]
I think I fixed the standard flag. Do you mean any other flag?

**Pull request merged**
